// (generated by Hierarchy DSL)



export type CommandType = "addIdentityToGroup" | "authenticateUser" | "confirmEmailAddress" | "createGroup" | "createUser" | "requestPasswordChange";

export type Command = IAddIdentityToGroupCommand | IConfirmEmailAddressCommand | ICreateGroupCommand | ICreateUserCommand | IAuthenticateUserCommand | IRequestPasswordChangeCommand;

export /* abstract */ interface ICommand {
    commandType: CommandType;
}

export interface IAddIdentityToGroupCommand extends ICommand {
    commandType: "addIdentityToGroup";
    groupId: string;
    memberId: string;
}

export interface IAuthenticateUserCommand extends ICommand {
    commandType: "authenticateUser";
    emailAddress: string;
    password: string;
}

export interface IConfirmEmailAddressCommand extends ICommand {
    commandType: "confirmEmailAddress";
    emailAddress: string;
    token: string;
}

export interface ICreateGroupCommand extends ICreateIdentityCommand {
    commandType: "createGroup";
}

export /* abstract */ interface ICreateIdentityCommand extends ICommand {
    name: string;
}

export interface ICreateUserCommand extends ICreateIdentityCommand {
    commandType: "createUser";
    emailAddress: string;
    password: string;
}

export interface IRequestPasswordChangeCommand extends ICommand {
    commandType: "requestPasswordChange";
    emailAddress: string;
}



